exchange:
  name: exchange
  currency:
    base: USD
    compare: RUB
  api:
    key: YOUR_APP_KEY
    urls:
      base: https://openexchangerates.org/api
      latest: /latest.json
      historical: /historical
gif:
  name: gif
  api:
    key: YOUR_API_KEY
    urls:
      base: https://api.giphy.com/v1
      rich: /gifs/random?tag=rich
      broke: /gifs/random?tag=broke
